#! /bin/bash
if [ $1 == 0 ] ; then
    compiler=gcc-12.1
elif [ $1 == 1 ] ; then
    compiler=icc
else 
    compiler=clang
fi
$compiler output2.c -gdwarf-4 -O2  -w -o output2 -lpthread
../../pin-3.21-98484-ge7cd811fd-gcc-linux/pin -t ../checkRead/obj-intel64/checkRead.so -- ./output2 func
objdump -dl output2 > disas